"""
One-off script: seed the "calls" collection with demo data (is_demo: true)
so admins have something to look at, without ever mixing into real users'
history (GET /api/v1/calls filters is_demo out for role != "admin").

demo_calls.json (next to this script) was already generated by converting
frontend/src/data/callIntelligenceData.ts's CALL_INTELLIGENCE_RECORDS object
into a JSON array. If you change that TS file, regenerate the JSON the same
way before re-running this script. To run it:

    cd backend
    python -m scripts.seed_demo_calls
"""
import asyncio
import json
import os

from app.database import db

DEMO_FILE = os.path.join(os.path.dirname(__file__), "demo_calls.json")


async def seed():
    if not os.path.exists(DEMO_FILE):
        print(f"No {DEMO_FILE} found. See this script's docstring for how to export it.")
        return

    with open(DEMO_FILE, "r", encoding="utf-8") as f:
        records = json.load(f)

    if not isinstance(records, list):
        print("demo_calls.json must contain a JSON array of call records.")
        return

    # Wipe previous demo seed so re-running this script is idempotent.
    await db["calls"].delete_many({"is_demo": True})

    for record in records:
        record["is_demo"] = True

    if records:
        await db["calls"].insert_many(records)

    print(f"Seeded {len(records)} demo call(s) into the 'calls' collection.")


if __name__ == "__main__":
    asyncio.run(seed())
